##### D&R URLS #####
ithaki_dr_url = "https://www.dr.com.tr/Yayinevi/ithaki-yayinlari/s=5119"
isbankasi_dr_url = "https://www.dr.com.tr/Yayinevi/is-bankasi-kultur-yayinlari/s=5109"
yky_dr_url = "https://www.dr.com.tr/Yayinevi/yapi-kredi-yayinlari/s=10615"
can_dr_url = "https://www.dr.com.tr/Yayinevi/can-yayinlari/s=1883"
dogan_dr_url = "https://www.dr.com.tr/yayinevi/dogan-kitap/s=2744"
kronik_dr_url = "https://www.dr.com.tr/yayinevi/kronik-kitap/s=5786"
sel_dr_url = "https://www.dr.com.tr/yayinevi/sel-yayincilik/s=8753"
altin_dr_url = "https://www.dr.com.tr/yayinevi/altin-kitaplar/s=510"
ayrinti_dr_url = "https://www.dr.com.tr/yayinevi/ayrinti-yayinlari/s=1113"
iletisim_dr_url = "https://www.dr.com.tr/yayinevi/kodlab/s=5693"

##### IDEFIX URLS #####
ithaki_idefix_url = "https://www.idefix.com/yayinevi/ithaki-yayinlari/s=5119"
isbankasi_idefix_url = "https://www.idefix.com/yayinevi/is-bankasi-kultur-yayinlari/s=5109"
yky_idefix_url = "https://www.idefix.com/yayinevi/yapi-kredi-yayinlari/s=10615"
can_idefix_url = "https://www.idefix.com/yayinevi/can-yayinlari/s=1883"
dogan_idefix_url = "https://www.idefix.com/yayinevi/dogan-kitap/s=2744"
kronik_idefix_url = "https://www.idefix.com/yayinevi/kronik-kitap/s=5786"
sel_idefix_url = "https://www.idefix.com/yayinevi/sel-yayincilik/s=8753"
altin_idefix_url = "https://www.idefix.com/yayinevi/altin-kitaplar/s=510"
ayrinti_idefix_url = "https://www.idefix.com/yayinevi/ayrinti-yayinlari/s=1113"
iletisim_idefix_url = "https://www.idefix.com/yayinevi/kodlab/s=5693"

##### BKMKITAP URLS #####
ithaki_bkm_url = "https://www.bkmkitap.com/ithaki-yayinlari"
isbankasi_bkm_url = "https://www.bkmkitap.com/is-bankasi-kultur-yayinlari"
yky_bkm_url = "https://www.bkmkitap.com/yapi-kredi-yayinlari"
can_bkm_url = "https://www.bkmkitap.com/can-yayinlari"
dogan_bkm_url = "https://www.bkmkitap.com/dogan-kitap"
kronik_bkm_url = "https://www.bkmkitap.com/kronik-kitap"
sel_bkm_url = "https://www.bkmkitap.com/sel-yayincilik"
altin_bkm_url = "https://www.bkmkitap.com/altin-kitaplar"
ayrinti_bkm_url = "https://www.bkmkitap.com/ayrinti-yayinlari"
iletisim_bkm_url = "https://www.bkmkitap.com/iletisim-yayinevi"

##### AMAZON URLS #####
ithaki_kidega_url = "https://kidega.com/yayinevi/ithaki-yayinlari-23341/?srt=ES"
isbankasi_kidega_url = "https://kidega.com/yayinevi/is-bankasi-kultur-yayinlari-001600/?srt=ES"
yky_kidega_url = "https://kidega.com/yayinevi/yapi-kredi-yayinlari-003271/?srt=ES"
can_kidega_url = "https://kidega.com/yayinevi/can-yayinlari-000645/?srt=ES"
dogan_kidega_url = "https://kidega.com/yayinevi/dogan-kitap-22607/?srt=ES"
kronik_kidega_url = "https://kidega.com/yayinevi/kronik-kitap-001874/?srt=ES"
sel_kidega_url = "https://kidega.com/yayinevi/sel-yayincilik-002800/?srt=ES"
altin_kidega_url = "https://kidega.com/yayinevi/altin-kitaplar-000189/?srt=ES"
ayrinti_kidega_url = "https://kidega.com/yayinevi/ayrinti-yayinlari-000397/?srt=ES"
iletisim_kidega_url = "https://kidega.com/yayinevi/iletisim-yayinevi-001509/?srt=ES"
